import { Movie, MovieDetails, Genre, PersonDetails, PersonCredits, CollectionDetails } from '@/types/cinema';

export const FALLBACK_GENRES: Genre[] = [
  { id: 28, name: 'Action' },
  { id: 12, name: 'Adventure' },
  { id: 16, name: 'Animation' },
  { id: 35, name: 'Comedy' },
  { id: 80, name: 'Crime' },
  { id: 99, name: 'Documentary' },
  { id: 18, name: 'Drama' },
  { id: 10751, name: 'Family' },
  { id: 14, name: 'Fantasy' },
  { id: 36, name: 'History' },
  { id: 27, name: 'Horror' },
  { id: 10402, name: 'Music' },
  { id: 9648, name: 'Mystery' },
  { id: 10749, name: 'Romance' },
  { id: 878, name: 'Science Fiction' },
  { id: 10770, name: 'TV Movie' },
  { id: 53, name: 'Thriller' },
  { id: 10752, name: 'War' },
  { id: 37, name: 'Western' },
];

export const FALLBACK_MOVIES: Movie[] = [
  {
    id: 872585,
    title: 'Oppenheimer',
    original_title: 'Oppenheimer',
    overview: 'The story of J. Robert Oppenheimer\'s role in the development of the atomic bomb during World War II, exploring the moral complexities, scientific triumph, and political fallout of the Manhattan Project.',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/7CENyUim29IEsaJhUxIGymCRvPu.jpg',
    vote_average: 8.1,
    vote_count: 8940,
    release_date: '2023-07-19',
    genre_ids: [18, 36],
    original_language: 'en',
    popularity: 285.4,
  },
  {
    id: 693134,
    title: 'Dune: Part Two',
    original_title: 'Dune: Part Two',
    overview: 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.',
    poster_path: '/6izwz7rsy95ARzTR3poZ8H6c5pp.jpg',
    backdrop_path: '/eZ239CUp1d6OryZEBPnO2n87gMG.jpg',
    vote_average: 8.2,
    vote_count: 5410,
    release_date: '2024-02-27',
    genre_ids: [878, 12],
    original_language: 'en',
    popularity: 310.2,
  },
  {
    id: 335984,
    title: 'Blade Runner 2049',
    original_title: 'Blade Runner 2049',
    overview: 'Thirty years after the events of the first film, a new blade runner, LAPD Officer K, unearths a long-buried secret that has the potential to plunge what\'s left of society into chaos.',
    poster_path: '/gajva2L0rPYkEWjzgFlBXCAVBE5.jpg',
    backdrop_path: '/gNdLJU9TxrpGx4dkZidjys3fyy0.jpg',
    vote_average: 7.9,
    vote_count: 13200,
    release_date: '2017-10-04',
    genre_ids: [878, 18, 9648],
    original_language: 'en',
    popularity: 145.8,
  },
  {
    id: 157336,
    title: 'Interstellar',
    original_title: 'Interstellar',
    overview: 'The adventures of a group of explorers who make use of a newly discovered wormhole to surpass the limitations on human space travel and conquer the vast distances involved in an interstellar voyage.',
    poster_path: '/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg',
    backdrop_path: '/8sNiAPPYU14PUepFNeSNGUTiHW.jpg',
    vote_average: 8.4,
    vote_count: 35100,
    release_date: '2014-11-05',
    genre_ids: [12, 18, 878],
    original_language: 'en',
    popularity: 210.5,
  },
  {
    id: 496243,
    title: 'Parasite',
    original_title: '기생충',
    overview: 'All unemployed, Ki-taek\'s family takes peculiar interest in the wealthy and glamorous Parks for their livelihood until they get entangled in an unexpected incident.',
    poster_path: '/7IiTTgloJzvGI1TAYymCfbfl3vT.jpg',
    backdrop_path: '/hiKmpZMGZsrkA3cdce8a7Dpos1j.jpg',
    vote_average: 8.5,
    vote_count: 18100,
    release_date: '2019-05-30',
    genre_ids: [35, 53, 18],
    original_language: 'ko',
    popularity: 120.9,
  },
  {
    id: 129,
    title: 'Spirited Away',
    original_title: '千と千尋の神隠し',
    overview: 'A young girl, Chihiro, becomes trapped in a strange new world of spirits. When her parents undergo a mysterious transformation, she must call upon the courage she never knew she had to free herself and her family.',
    poster_path: '/39wmItIWsg5sZMyRUHLkWBcuVCM.jpg',
    backdrop_path: '/6oaL4DP75yABrd5EbC4H2zq5ghc.jpg',
    vote_average: 8.5,
    vote_count: 16500,
    release_date: '2001-07-20',
    genre_ids: [16, 10751, 14],
    original_language: 'ja',
    popularity: 115.4,
  },
  {
    id: 238,
    title: 'The Godfather',
    original_title: 'The Godfather',
    overview: 'Spanning the years 1945 to 1955, a chronicle of the fictional Italian-American Corleone crime family. When organized crime family patriarch, Vito Corleone barely survives an attempt on his life, his youngest son, Michael steps in to take care of the would-be killers.',
    poster_path: '/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    backdrop_path: '/tSPT36ZKlP2WVHJLM4cQPLSzv3b.jpg',
    vote_average: 8.7,
    vote_count: 20200,
    release_date: '1972-03-14',
    genre_ids: [18, 80],
    original_language: 'en',
    popularity: 180.2,
  },
  {
    id: 155,
    title: 'The Dark Knight',
    original_title: 'The Dark Knight',
    overview: 'Batman raises the stakes in his war on crime. With the help of Lt. Jim Gordon and District Attorney Harvey Dent, Batman sets out to dismantle the remaining criminal organizations that plague the streets.',
    poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop_path: '/9FE5eD92WfVCiivM9Pq9GVSrlWk.jpg',
    vote_average: 8.5,
    vote_count: 32600,
    release_date: '2008-07-16',
    genre_ids: [18, 28, 80, 53],
    original_language: 'en',
    popularity: 195.3,
  },
  {
    id: 666277,
    title: 'Past Lives',
    original_title: 'Past Lives',
    overview: 'Nora and Hae Sung, two deeply connected childhood friends, are wrested apart after Nora’s family emigrates from South Korea. Two decades later, they are reunited in New York for one fateful week as they confront notions of destiny, love, and the choices that make a life.',
    poster_path: '/k3waqVXSnvCZWfJYNtdamTgTtTA.jpg',
    backdrop_path: '/7HR38hMBl23lf38MAN63y4pKsHz.jpg',
    vote_average: 7.9,
    vote_count: 1420,
    release_date: '2023-06-02',
    genre_ids: [18, 10749],
    original_language: 'en',
    popularity: 92.4,
  },
  {
    id: 438631,
    title: 'Dune',
    original_title: 'Dune',
    overview: 'Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people.',
    poster_path: '/v1tRXZ4JtD2Iv6fjkPvT4GiwslV.jpg',
    backdrop_path: '/zRKQW58MBEY078AxkHxEJzUskCl.jpg',
    vote_average: 7.8,
    vote_count: 11800,
    release_date: '2021-09-15',
    genre_ids: [878, 12],
    original_language: 'en',
    popularity: 160.7,
  },
  {
    id: 27205,
    title: 'Inception',
    original_title: 'Inception',
    overview: 'Cobb, a skilled thief who commits corporate espionage by infiltrating the subconscious of his targets is offered a chance to regain his old life as payment for a task considered to be impossible: "inception", the implantation of another person\'s idea into a target\'s subconscious.',
    poster_path: '/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg',
    backdrop_path: '/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    vote_average: 8.4,
    vote_count: 36200,
    release_date: '2010-07-15',
    genre_ids: [28, 878, 12],
    original_language: 'en',
    popularity: 175.6,
  },
  {
    id: 77,
    title: 'Memento',
    original_title: 'Memento',
    overview: 'Leonard Shelby is tracking down the man who raped and murdered his wife. The difficulty of locating his wife\'s killer, however, is compounded by the fact that he suffers from a rare, untreatable form of short-term memory loss.',
    poster_path: '/nzlv62aC0octS5AklAiWpXLX9Z0.jpg',
    backdrop_path: '/7Wev9JMo6R5XAfz2KDvXb7oPMmy.jpg',
    vote_average: 8.2,
    vote_count: 14900,
    release_date: '2000-10-11',
    genre_ids: [9648, 53],
    original_language: 'en',
    popularity: 78.3,
  },
  {
    id: 680,
    title: 'Pulp Fiction',
    original_title: 'Pulp Fiction',
    overview: 'A burger-loving hit man, his philosophical partner, a drug-addled gangster\'s moll and a washed-up boxer converge in this sprawling, comedic crime caper. Their adventures unfurl in three stories that ingeniously trip back and forth in time.',
    poster_path: '/vQWk5YBFWF4bZaofAbv0tShwBvQ.jpg',
    backdrop_path: '/suaEOtk1N1sgg2MTM7oZd2cfVp3.jpg',
    vote_average: 8.5,
    vote_count: 27100,
    release_date: '1994-09-10',
    genre_ids: [53, 80],
    original_language: 'en',
    popularity: 110.5,
  },
  {
    id: 603,
    title: 'The Matrix',
    original_title: 'The Matrix',
    overview: 'Set in the 22nd century, The Matrix tells the story of a computer hacker who joins a group of underground insurgents fighting the vast and powerful computers who now rule the earth.',
    poster_path: '/dXNAPwY7VrqMAo51EKhhCJfaGb5.jpg',
    backdrop_path: '/lrtSb1skJayPydZk0OSMAKjBOVe.jpg',
    vote_average: 8.2,
    vote_count: 25300,
    release_date: '1999-03-30',
    genre_ids: [28, 878],
    original_language: 'en',
    popularity: 130.4,
  },
  {
    id: 78,
    title: 'Blade Runner',
    original_title: 'Blade Runner',
    overview: 'In the smog-choked dystopian Los Angeles of 2019, blade runner Rick Deckard is called out of retirement to terminate a quartet of replicants who have escaped to Earth seeking their creator.',
    poster_path: '/63N9uy8nd9j7Eog2axPQ8lbr3Wj.jpg',
    backdrop_path: '/2spEHYDcyE9r9mS7AFEscfKVDzO.jpg',
    vote_average: 7.9,
    vote_count: 13600,
    release_date: '1982-06-25',
    genre_ids: [878, 18, 53],
    original_language: 'en',
    popularity: 98.6,
  },
  {
    id: 694,
    title: 'The Shining',
    original_title: 'The Shining',
    overview: 'Jack Torrance accepts a caretaker job at the Overlook Hotel, where he, his wife Wendy and their psychic son Danny settle in for the winter, unaware that an evil and sinister presence drives Jack towards violent madness.',
    poster_path: '/uAR0AWqhQL1hQa69UDEbb2rE5Wx.jpg',
    backdrop_path: '/AdKA2F1SzYPhSZdEbjH1Zh75UVQ.jpg',
    vote_average: 8.2,
    vote_count: 17200,
    release_date: '1980-05-23',
    genre_ids: [27, 53],
    original_language: 'en',
    popularity: 94.2,
  },
  {
    id: 28,
    title: 'Apocalypse Now',
    original_title: 'Apocalypse Now',
    overview: 'At the height of the Vietnam war, Captain Benjamin Willard is sent on a dangerous mission into Cambodia to assassinate a renegade Colonel who has won the trust of a local tribe.',
    poster_path: '/gQB8Y5RCMkv2zwzFHbUJX3kAhvA.jpg',
    backdrop_path: '/49fzLedFVKgGgFChLMuulDJBY1c.jpg',
    vote_average: 8.3,
    vote_count: 8100,
    release_date: '1979-08-15',
    genre_ids: [18, 10752],
    original_language: 'en',
    popularity: 75.8,
  },
];

export const FALLBACK_MOVIE_DETAILS: Record<number, MovieDetails> = {
  872585: {
    id: 872585,
    title: 'Oppenheimer',
    original_title: 'Oppenheimer',
    tagline: 'The world forever changes.',
    overview: 'The story of J. Robert Oppenheimer\'s role in the development of the atomic bomb during World War II, exploring the moral complexities, scientific triumph, and political fallout of the Manhattan Project.',
    poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
    backdrop_path: '/7CENyUim29IEsaJhUxIGymCRvPu.jpg',
    vote_average: 8.1,
    vote_count: 8940,
    release_date: '2023-07-19',
    runtime: 181,
    status: 'Released',
    budget: 100000000,
    revenue: 957800000,
    imdb_id: 'tt15398776',
    homepage: 'https://www.oppenheimermovie.com',
    original_language: 'en',
    genres: [
      { id: 18, name: 'Drama' },
      { id: 36, name: 'History' },
    ],
    belongs_to_collection: null,
    production_companies: [
      { id: 33, name: 'Universal Pictures', logo_path: '/8lvHyhjr8oUKOOy2dKXo3hub4ba.png', origin_country: 'US' },
      { id: 9996, name: 'Syncopy', logo_path: '/z2wlyq6nB54nCwb7B4i64z5c2c.png', origin_country: 'GB' },
    ],
    spoken_languages: [
      { english_name: 'English', iso_639_1: 'en', name: 'English' },
      { english_name: 'German', iso_639_1: 'de', name: 'Deutsch' },
    ],
    credits: {
      cast: [
        { id: 2037, name: 'Cillian Murphy', character: 'J. Robert Oppenheimer', profile_path: '/2lKs67r7FI4bPu0AXxMUJZxmUXn.jpg', order: 0 },
        { id: 5081, name: 'Emily Blunt', character: 'Katherine "Kitty" Oppenheimer', profile_path: '/5nCSG5TL1bP1geD8aaBfaLnLLCD.jpg', order: 1 },
        { id: 1892, name: 'Matt Damon', character: 'Leslie Groves', profile_path: '/aCvBXTAR9B1qRjIRzMBYhhbm1fR.jpg', order: 2 },
        { id: 3223, name: 'Robert Downey Jr.', character: 'Lewis Strauss', profile_path: '/5qHNjhtjMD4YWH3UP0rm4tKwxCL.jpg', order: 3 },
        { id: 1373737, name: 'Florence Pugh', character: 'Jean Tatlock', profile_path: '/1Uvfh7xL4U2evkhs0M3C7BbBYFf.jpg', order: 4 },
        { id: 1100, name: 'Kenneth Branagh', character: 'Niels Bohr', profile_path: '/5eMo8D7h1XrSu6ZN4UXhPcS6YNG.jpg', order: 5 },
      ],
      crew: [
        { id: 525, name: 'Christopher Nolan', job: 'Director', department: 'Directing', profile_path: '/xuAIuYSmsUzKlUMBFGVZaWsY3DZ.jpg' },
        { id: 525, name: 'Christopher Nolan', job: 'Writer', department: 'Writing', profile_path: '/xuAIuYSmsUzKlUMBFGVZaWsY3DZ.jpg' },
        { id: 559, name: 'Hoyte van Hoytema', job: 'Director of Photography', department: 'Camera', profile_path: '/uyWeYsERTTLjpjkE79QeSETLIoA.jpg' },
        { id: 64149, name: 'Ludwig Göransson', job: 'Original Music Composer', department: 'Sound', profile_path: '/o5BXNCGeMiYS6AlRGigQCGVbr7K.jpg' },
      ],
    },
    videos: {
      results: [
        {
          id: 'oppenheimer_trailer',
          key: 'uYPbbksJxIg',
          name: 'Official Trailer',
          site: 'YouTube',
          type: 'Trailer',
          official: true,
        },
      ],
    },
    similar: {
      page: 1,
      results: FALLBACK_MOVIES.slice(2, 6),
      total_pages: 1,
      total_results: 4,
    },
    recommendations: {
      page: 1,
      results: FALLBACK_MOVIES.slice(1, 5),
      total_pages: 1,
      total_results: 4,
    },
  },
  693134: {
    id: 693134,
    title: 'Dune: Part Two',
    original_title: 'Dune: Part Two',
    tagline: 'Long live the fighters.',
    overview: 'Follow the mythic journey of Paul Atreides as he unites with Chani and the Fremen while on a warpath of revenge against the conspirators who destroyed his family.',
    poster_path: '/6izwz7rsy95ARzTR3poZ8H6c5pp.jpg',
    backdrop_path: '/eZ239CUp1d6OryZEBPnO2n87gMG.jpg',
    vote_average: 8.2,
    vote_count: 5410,
    release_date: '2024-02-27',
    runtime: 166,
    status: 'Released',
    budget: 190000000,
    revenue: 714444358,
    imdb_id: 'tt15239678',
    homepage: 'https://www.dunemovie.com',
    original_language: 'en',
    genres: [
      { id: 878, name: 'Science Fiction' },
      { id: 12, name: 'Adventure' },
    ],
    belongs_to_collection: {
      id: 726871,
      name: 'Dune Collection',
      poster_path: '/v1tRXZ4JtD2Iv6fjkPvT4GiwslV.jpg',
      backdrop_path: '/zRKQW58MBEY078AxkHxEJzUskCl.jpg',
    },
    production_companies: [
      { id: 923, name: 'Legendary Pictures', logo_path: '/5U25nS5Svhz6k0y0hY0b.png', origin_country: 'US' },
      { id: 174, name: 'Warner Bros. Pictures', logo_path: '/ky0uh5b81c4z5c2c.png', origin_country: 'US' },
    ],
    spoken_languages: [
      { english_name: 'English', iso_639_1: 'en', name: 'English' },
    ],
    credits: {
      cast: [
        { id: 1190668, name: 'Timothée Chalamet', character: 'Paul Atreides', profile_path: '/dFxpwRpmzpVfP1zjluH68DeQhyj.jpg', order: 0 },
        { id: 505710, name: 'Zendaya', character: 'Chani', profile_path: '/3WdOloHpjtjL96uVOhFRRCcYSwq.jpg', order: 1 },
        { id: 933238, name: 'Rebecca Ferguson', character: 'Lady Jessica Atreides', profile_path: '/ra53cM1aNmdH0aFhj8yBqPOj2fb.jpg', order: 2 },
        { id: 83002, name: 'Javier Bardem', character: 'Stilgar', profile_path: '/zfRID0jx8DKBluPGU9xtk9sZWUt.jpg', order: 3 },
        { id: 1399, name: 'Stellan Skarsgård', character: 'Baron Vladimir Harkonnen', profile_path: '/63NIBXye0iMtbEMA8V6o08s0fuG.jpg', order: 4 },
        { id: 16828, name: 'Austin Butler', character: 'Feyd-Rautha Harkonnen', profile_path: '/atdAs4pFGjUQ4m2W8kJYly7N6cC.jpg', order: 5 },
      ],
      crew: [
        { id: 137427, name: 'Denis Villeneuve', job: 'Director', department: 'Directing', profile_path: '/zdDx9Xs93UIrJFWYApYR28J8M6b.jpg' },
        { id: 137427, name: 'Denis Villeneuve', job: 'Screenplay', department: 'Writing', profile_path: '/zdDx9Xs93UIrJFWYApYR28J8M6b.jpg' },
        { id: 947, name: 'Hans Zimmer', job: 'Original Music Composer', department: 'Sound', profile_path: '/tpQnDeHY15szIXvpnhlprufz4d.jpg' },
        { id: 153, name: 'Greig Fraser', job: 'Director of Photography', department: 'Camera', profile_path: '/j8rIiOSdBjtDL5vji8m5BtChZou.jpg' },
      ],
    },
    videos: {
      results: [
        {
          id: 'dune2_trailer',
          key: 'Way9Dexny3w',
          name: 'Official Trailer 3',
          site: 'YouTube',
          type: 'Trailer',
          official: true,
        },
      ],
    },
    similar: {
      page: 1,
      results: FALLBACK_MOVIES.slice(0, 4),
      total_pages: 1,
      total_results: 4,
    },
    recommendations: {
      page: 1,
      results: [FALLBACK_MOVIES[2], FALLBACK_MOVIES[3], FALLBACK_MOVIES[0]],
      total_pages: 1,
      total_results: 3,
    },
  },
};

export const FALLBACK_COLLECTION: CollectionDetails = {
  id: 726871,
  name: 'Dune Collection',
  overview: 'The sweeping Frank Herbert cinematic saga directed by Denis Villeneuve chronicling the perilous destiny of House Atreides on the desert world of Arrakis.',
  poster_path: '/v1tRXZ4JtD2Iv6fjkPvT4GiwslV.jpg',
  backdrop_path: '/zRKQW58MBEY078AxkHxEJzUskCl.jpg',
  parts: [
    FALLBACK_MOVIES[9], // Dune 2021
    FALLBACK_MOVIES[1], // Dune Part Two 2024
  ],
};

export const FALLBACK_PERSON: PersonDetails = {
  id: 525,
  name: 'Christopher Nolan',
  biography: 'Christopher Edward Nolan CBE is a British-American filmmaker known for his Hollywood blockbusters with complex storytelling. He is widely considered one of the leading filmmakers of the 21st century. His films have grossed more than $6 billion worldwide and have garnered 36 Academy Award nominations and 11 wins.',
  birthday: '1970-07-30',
  deathday: null,
  gender: 2,
  known_for_department: 'Directing',
  place_of_birth: 'London, England, UK',
  profile_path: '/xuAIuYSmsUzKlUMBFGVZaWsY3DZ.jpg',
  popularity: 88.5,
  imdb_id: 'nm0634240',
  homepage: null,
};

export const FALLBACK_PERSON_CREDITS: PersonCredits = {
  id: 525,
  cast: [],
  crew: [
    {
      id: 872585,
      title: 'Oppenheimer',
      job: 'Director',
      department: 'Directing',
      release_date: '2023-07-19',
      poster_path: '/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg',
      backdrop_path: '/7CENyUim29IEsaJhUxIGymCRvPu.jpg',
      vote_average: 8.1,
      vote_count: 8940,
      overview: 'The story of J. Robert Oppenheimer\'s role in the development of the atomic bomb.',
      credit_id: 'oppenheimer_dir',
      genre_ids: [18, 36],
    },
    {
      id: 157336,
      title: 'Interstellar',
      job: 'Director',
      department: 'Directing',
      release_date: '2014-11-05',
      poster_path: '/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg',
      backdrop_path: '/8sNiAPPYU14PUepFNeSNGUTiHW.jpg',
      vote_average: 8.4,
      vote_count: 35100,
      overview: 'Explorers travel through a wormhole in space in an attempt to ensure humanity\'s survival.',
      credit_id: 'interstellar_dir',
      genre_ids: [12, 18, 878],
    },
    {
      id: 27205,
      title: 'Inception',
      job: 'Director',
      department: 'Directing',
      release_date: '2010-07-15',
      poster_path: '/xlaY2zyzMfkhk0HSC5VUwzoZPU1.jpg',
      backdrop_path: '/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
      vote_average: 8.4,
      vote_count: 36200,
      overview: 'A thief who enters the dreams of others to steal secrets.',
      credit_id: 'inception_dir',
      genre_ids: [28, 878, 12],
    },
    {
      id: 155,
      title: 'The Dark Knight',
      job: 'Director',
      department: 'Directing',
      release_date: '2008-07-16',
      poster_path: '/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
      backdrop_path: '/9FE5eD92WfVCiivM9Pq9GVSrlWk.jpg',
      vote_average: 8.5,
      vote_count: 32600,
      overview: 'Batman fights the menace known as the Joker.',
      credit_id: 'dark_knight_dir',
      genre_ids: [18, 28, 80],
    },
    {
      id: 77,
      title: 'Memento',
      job: 'Director',
      department: 'Directing',
      release_date: '2000-10-11',
      poster_path: '/nzlv62aC0octS5AklAiWpXLX9Z0.jpg',
      backdrop_path: '/7Wev9JMo6R5XAfz2KDvXb7oPMmy.jpg',
      vote_average: 8.2,
      vote_count: 14900,
      overview: 'A man with short-term memory loss attempts to track down his wife\'s murderer.',
      credit_id: 'memento_dir',
      genre_ids: [9648, 53],
    },
  ],
};
